### PR TITLE
Update with master

### PR DESCRIPTION
**Pull request by dhcole**
Pulls in upstream commits to upgrade packages and fix tests.

### CODE REVIEW

**Comment by ultrasaurus** [comment]
Wonderful.  Will leave open for a few hours in case @DavidEBest, @polastre or anyone else wants to review / comment.

**Comment by polastre** [comment]
@ultrasaurus / @dhcole since CI is not hooked up, would like confirmation that all the tests are passing.

Otherwise looks good, and I know this fixes a few bugs with `cloneDeep`.

**Comment by dhcole** [comment]
@polastre :+1: tests pass with this merged locally: https://github.com/18F/sails-postgresql/pull/2#issuecomment-72052804

**Comment by polastre** [comment]
then I'm :+1: once #2 is merged.

**Pull request merged**
